```{r}
rm(list = ls())

PAQUETES <- c("dplyr","tidyverse","ggplot2","eurostat","readxl")

for (el in PAQUETES){
  if (!require(el, character.only = TRUE)) {
    install.packages(el, repos = "https://cloud.r-project.org")
    require(el, character.only = TRUE)
  }
}
```

load country names, dictionary 
```{r}
  #load EU country names
  EU_countries<-read_excel("./dictionaries/EU_countries.xlsx") %>% 
    rename(country_code=code,country_name=name)
  EU_Countries_names_dict<- setNames(EU_countries$country_name, EU_countries$country_code)
  
  # load to the dictionary file
dictionary <- read_rds("./dictionaries/variable_dictionary.RDS")


```



create function to load and store data
```{r}

# Function to load and save country data
load_data_country <- function(series, alias, dictionary) {
  print(paste0("loading ", series, " ", alias))



  # Try to load data using get_eurostat
  data <- try(
    get_eurostat(series, filters = list(geo = pull(EU_countries, country_code))) %>%
      filter(!is.na(values)), # Filter out NAs
    silent = TRUE
  )
    
  # Check if an error occurred during get_eurostat call
  if ("try-error" %in% class(data)){
    message("Error in series code: ", series)
    return(NULL) # Exit the function on error
  }
  # Recode columns

  for (variable in colnames(data)) {
      if (variable %in% c("geo","time","TIME_PERIOD","c_birth")) {
        #skip
      }
      else if (variable %in% tolower(unique(dictionary$variable_code))) {
        #filter and unnest dictionary
        dictionary %>% 
          filter(variable_code==toupper(variable)) %>% 
          unnest(cols=data) -> variable_dictionary
        #get variable name
        dictionary %>% 
          filter(variable_code==toupper(variable)) %>% 
          pull(variable_name) -> variable_name
        #create replacing dictionary
        replacement_dictionary <- setNames(variable_dictionary$name, variable_dictionary$code)
        data <- data %>%
          mutate(!!sym(variable_name) := recode(!!sym(variable), !!!replacement_dictionary)) %>% 
          select(-!!sym(variable))
        # !!! splits a vector into individual arguments for a function
        # !!sym() is a way to convert the string sheet into a symbol that dplyr can understand as a column name.
      }
  }
  # Save the data
  save(data, file = paste0("./data/country/", alias, ".RData"))
  print(paste0("series ", series, " ", alias, " loaded"))

  # Clean up
  rm(data)
  gc()
}

```

loading country data
```{r}
statistics<-read_excel("./loading_statistics.xlsx",sheet="country" )

for (ii in 1:nrow(statistics)) {
  load_data_country(statistics$code[ii],statistics$alias[ii],dictionary)
}


```
create geo and time table for the star schema in countries
```{r}
# List all files in the "./data" directory
data_files <- list.files("./data/country")

# Exclude "geo_dates" from the list
data_files <- data_files[data_files != "geo_dates.RData"]


geo_dates <- data.frame()
for (file in data_files) {
  load(paste0("./data/country/",file))
  print(file)
  data %>% 
    select(geo,time) %>%
    left_join(EU_countries,by=c("geo"="country_code")) %>% 
    rbind(geo_dates) %>% 
    unique() ->geo_dates
}
save(geo_dates, file = paste0("./data/country/","geo_dates", ".RData"))

```

function to load regional data
```{r}
load_data_region <- function(series,alias,dictionary){
  EU_countries<-read_excel("./dictionaries/EU_countries.xlsx") %>% 
  rename(country_code=code,country_name=name)
  #load data
  data <- get_eurostat(series) %>% 
    filter(!is.na(values)) %>%  #filter out NAs
    mutate(country_code=substr(geo,1,2)) %>% 
    filter(country_code %in% EU_countries$country_code) %>% 
    filter(nchar(geo)==4) %>% 
    select(-country_code) # in is in the date-country data
  #recode columns
  for (variable in colnames(data)) {
      if (variable %in% c("geo","time","TIME_PERIOD")) {
        #skip
      }
      else if (variable %in% tolower(unique(dictionary$variable_code))) {
        #filter and unnest dictionary
        dictionary %>% 
          filter(variable_code==toupper(variable)) %>% 
          unnest(cols=data) -> variable_dictionary
        #get variable name
        dictionary %>% 
          filter(variable_code==toupper(variable)) %>% 
          pull(variable_name) -> variable_name
        #create replacing dictionary
        replacement_dictionary <- setNames(variable_dictionary$name, variable_dictionary$code)
        data <- data %>%
          mutate(!!sym(variable_name) := recode(!!sym(variable), !!!replacement_dictionary)) %>% 
          select(-!!sym(variable))
        # !!! splits a vector into individual arguments for a function
        # !!sym() is a way to convert the string sheet into a symbol that dplyr can understand as a column name.
    }
  }
  
  save(data, file = paste0("./data/region/",alias, ".RData"))
  print(paste0("series ",series," ", alias, " loaded"))
  rm(data)
  gc()
}
```

loading region data
```{r}
statistics<-read_excel("./loading_statistics.xlsx",sheet="region" )

for (ii in 1:nrow(statistics)) {
  load_data_region(statistics$code[ii],statistics$alias[ii],dictionary)
}

```
create geo and time table for the star schema in regions
```{r}
# List all files in the "./data" directory
data_files <- list.files("./data/region")

# Exclude "geo_dates" from the list
data_files <- data_files[data_files != "geo_dates.RData"]

NUTS2<-read_excel("./dictionaries/NUTS2.xlsx" ) %>% 
  rename(geo=NUTS2)

geo_dates <- data.frame()
for (file in data_files) {
  load(paste0("./data/region/",file))
  print(file)
  data %>% 
    select(geo,TIME_PERIOD) %>%
    left_join(NUTS2,by="geo") %>% 
    rbind(geo_dates) %>% 
    unique() ->geo_dates
}
#include country names and codes
geo_dates %>% 
  mutate(country_code = substr(geo,1,2)) %>% 
  left_join(EU_countries,by="country_code") -> geo_dates
save(geo_dates, file = paste0("./data/region/","geo_dates", ".RData"))

```

funtion to load city data
```{r}
load_data_city <- function(series,alias,dictionary,sheet_names){
  EU_countries<-read_excel("./dictionaries/EU_countries.xlsx") %>% 
  rename(country_code=code,country_name=name)
  #load data
  data <- get_eurostat(series) %>%
    filter(!is.na(values)) %>%  #filter out NAs
    mutate(country_code=substr(cities,1,2)) %>% 
    filter(country_code %in% EU_countries$country_code) %>% 
    filter(nchar(cities)==6) %>% 
    select(-country_code) %>% 
    rename(city_code=cities)
  #recode columns
  for (variable in colnames(data)) {
      if (variable %in% c("geo","time","TIME_PERIOD")) {
        #skip
      }
      else if (variable %in% tolower(unique(dictionary$variable_code))) {
        #filter and unnest dictionary
        dictionary %>% 
          filter(variable_code==toupper(variable)) %>% 
          unnest(cols=data) -> variable_dictionary
        #get variable name
        dictionary %>% 
          filter(variable_code==toupper(variable)) %>% 
          pull(variable_name) -> variable_name
        #create replacing dictionary
        replacement_dictionary <- setNames(variable_dictionary$name, variable_dictionary$code)
        data <- data %>%
          mutate(!!sym(variable_name) := recode(!!sym(variable), !!!replacement_dictionary)) %>% 
          select(-!!sym(variable))
        # !!! splits a vector into individual arguments for a function
        # !!sym() is a way to convert the string sheet into a symbol that dplyr can understand as a column name.
    }
  }
  
  save(data, file = paste0("./data/city/",alias, ".RData"))
  print(paste0("series ",series," ", alias, " loaded"))
  rm(data)
  gc()
}

```
load city data
```{r}

statistics<-read_excel("./loading_statistics.xlsx",sheet="city" )

for (ii in 1:nrow(statistics)) {
  load_data_city(statistics$code[ii],statistics$alias[ii],dictionary,sheet_names)
}


```
create geo and time table for the star schema in cities
```{r}
# List all files in the "./data" directory
data_files <- list.files("./data/city")

# Exclude "geo_dates" from the list
data_files <- data_files[data_files != "geo_dates.RData"]

cities<-read_excel("./dictionaries/cities.xlsx" ) %>% 
  rename(city_name=NAME)

geo_dates <- data.frame()
for (file in data_files) {
  load(paste0("./data/city/",file))
  print(file)
  data %>% 
    select(city_code,TIME_PERIOD) %>%
    left_join(cities,by=c("city_code"="CODE")) %>% 
    rbind(geo_dates) %>% 
    unique() ->geo_dates
}
#include country names and codes
geo_dates %>% 
  mutate(country_code = substr(city_code,1,2)) %>% 
  left_join(EU_countries,by="country_code") -> geo_dates
save(geo_dates, file = paste0("./data/city/","geo_dates", ".RData"))

```
